### ISSUE TITLE
Channels must have an exclamation mark in their name

### ISSUE THREAD

**Issue by ynaciri** [CJWorkbench/channels_rabbitmq#16]
Hi,

I tried using channels_rabbitmq for convenience, since I already use it with celery, and I tried validating it with channels tutorial for redis but kept getting this assert error :
```
  File "(...)\venv\lib\site-packages\channels_rabbitmq\core.py", line 145, in send
    assert "!" in channel
```

So, I then went reading the source code to figure out that you enforce having an exclamation mark in the channel name.

For information, I'm using the following software versions :

* channels==2.2.0
* channels-rabbitmq==1.1.5
* Django==2.2.1

Could you remove that assert ? Or does it have any use except annoying us with undocumented limitations ?

**Comment by adamhooper** [comment]
This is a dup of #11 ... and I've written a long comment describing why the assertion is there.

(In short: yes, this assertion violates the Channels spec; but that's because the Channels spec describes two completely different services: Websockets and work queues. `channels_rabbitmq` only focuses on the Websockets for now. Pull requests welcome.)
