### ISSUE TITLE
Every expired group will raise RuntimeError

### ISSUE THREAD

**Issue by ndavydovdev** [CJWorkbench/channels_rabbitmq#18]
![Screenshot 2019-10-28 at 18 41 57](https://user-images.githubusercontent.com/21359293/67693391-a76dda00-f9b2-11e9-81f9-c35847d041f4.png)

This code will raise error every time if `if channels[other_key] < now` is True.
I fixed it by raise `group_expiry`  param in the config.

**Comment by ndavydovdev** [comment]
I have created pull request to fix it
#19

**Comment by adamhooper** [comment]
Thank you for reporting this error -- and thank you for the pull request!

As documented in `README.rst`, you were probably right to increase `group_expiry`. The setting and default only exist because the [Channel Layer Specification](https://channels.readthedocs.io/en/latest/channel_layer_spec.html) requires it.

After thinking on it for a while, I've developed the opinion that the spec is wrong. I've filed https://github.com/django/channels/issues/1371 to nix `group_expiry` from the Channel Layer Specification. I don't see a good reason to expire connections.

... but let me ask you, @ndavydovdev: how did you encounter this bug? Do you actually want groups to expire? If so, why?

**Comment by ndavydovdev** [comment]
@adamhooper Thank you for your response! We have the system which manages user sessions and when the user stays in the one session(one group, one connection) a long time -> his group expires -> got this error. I think nobody uses standard `group_expiry ` or fix this error by increasing to one year as recommended. in fact, this code will never work properly and if somebody wants to use this `group_expiry` with very small error, this person will get this every time

**Comment by adamhooper** [comment]
Awesome -- that's what I figured. Thanks for confirming.

I'll merge your pull request (and add a unit test). The expected result will be: the subscription disappears and nothing else breaks.

I'll also warn users on connect, if they're using the default value of `group_expiry`, to increase it. This advocacy may help change the specification.

**Comment by adamhooper** [comment]
I still haven't added a warning. I was waiting on Django-channels devs for feedback on the spec. I still haven't heard back....

**Comment by adamhooper** [comment]
... actually, come to think of it ... I'm going to disable this feature entirely. I don't think any user wants finite `group_expiry`. I consider it an error in the spec.
