### ISSUE TITLE
[Usage Question] Guidance on use with Amazon MQ - AMQP over TLS

### ISSUE THREAD

**Issue by kevindice** [CJWorkbench/channels_rabbitmq#22]
I'm having trouble getting `channels_rabbbitmq` to talk to `Amazon MQ` via AMQP over TLS. 

I am able to ping the Amazon MQ host from my django/daphne host, networking all checks out, and security groups are wide open.  So, I suspect some protocol level issue.

The line (in our code) `async_to_sync(channel_layer.group_send)(f'user-{user.id}', message)` seems to just hang.

Has anyone had success using `channels_rabbitmq` with Amazon MQ.  Would like to help add a usage note to the docs once I get this figured out.  Migrating from `channels_redis` due to bizarre dropped messages.

Python 3.8
```
amqp==2.5.2
asgiref==3.2.2
channels==2.3.0
channels-rabbitmq==1.2.0
daphne==2.3.0
Django==2.2.8
```

Django settings:

```
import ssl

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_rabbitmq.core.RabbitmqChannelLayer',
        'CONFIG': {
            'ssl_context': ssl.create_default_context(),
            'hosts': os.environ['CHANNEL_LAYERS_RABBITMQ_HOST']
        }
    }
}
```

value of `CHANEL_LAYERS_RABBITMQ_HOST`: `amqp://$username:$password@$amazonmqId-1.mq.us-east-1.amazonaws.com:5671/asgi`

(with username, passoword, and the amazonMq instance ID substituted of course)

**Comment by adamhooper** [comment]
`channels_rabbitmq` doesn't support AmazonMQ. You'll need to fork this project.

RabbitMQ uses AMQP 0.9.1. AmazonMQ is Apache ActiveMQ, which supports AMQP 1.0. Those two protocols are vastly different. For example: `channels_rabbitmq` sends messages to an AMQP 0.9.1 "exchange". AMQP 1.0 does not define an "exchange".

Most Python asyncio AMQP libraries I'm aware of only work on AMQP 0.9.1. The only one I found for AMQP 1.0 is https://pypi.org/project/uamqp/

On top of the different protocol, `channels_rabbitmq` uses some RabbitMQ extensions that aren't even in AMQP 0.9.1. `x-max-length` implements the layer's `remote_capacity` and `x-message-ttl` implements the layer's `expiry`. These settings help limit the damage caused by bugs or DoS attacks.
