### ISSUE TITLE
Question on using Celery with Channels

### ISSUE THREAD

**Issue by ShaheedHaque** [CJWorkbench/channels_rabbitmq#25]
Hi,

First, thanks for this library: it's just what I wanted/needed!

Now, I was having some difficulty combining Celery with Channels (https://groups.google.com/g/django-users/c/KWJ1r2MN478) which I "solved" with this monstrosity:
```   
@task   <<<< mark as a Celery task
def import_all(...): <<<<<<< wrapper 1
    async_to_sync(_import_all)(...)

async def _import_all(...): <<<<<< wrapper 2
    await database_sync_to_async(__import_all)(...)

def __import_all(...):   <<<<<<<<<< original code
    ...database access...
    async_to_sync(group_send)(...)
```
TBH, being a newbie when it comes to Python async code, I'm not very clear on exactly why I needed these wrappers, but this mostly works **except** that it turns out that Celery is not very happy with - but can recover from - this exception:
```
2020-08-23 13:00:26,805 [ERROR] ForkPoolWorker-14: 
Traceback (most recent call last):
  File "/main/srhaque/Innovatieltd/source/paiyroll/views/importer_views.py", line 297, in import_all
    async_to_sync(_import_all)(clazz, files_data, tmpdir, client, email, check_data)
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 120, in __call__
    loop_future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 173, in _run_event_loop
    loop.close()
  File "/usr/local/lib/python3.8/dist-packages/channels_rabbitmq/core.py", line 118, in _wrapper
    self.run_until_complete(connection.close())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
```
I logged this by modifying the wrapper 1 code like this (since this does not propagate the exception, it also leaves Celery blissfully unaware/happy):
```
@task
def import_all(...):
    try:
        async_to_sync(_import_all)(...)
    except asyncio.exceptions.CancelledError as e:
        logger.exception(e)
```
Given that the original code seems to work just fine, I'm wondering if there a way to tell **why** the cancellation is taking place? Is catching this exception even safe? (I'm aware that the docs advise that this exception should normally be allowed to propagate).

Any thoughts/advice welcome.

Thanks, Shaheed

**Comment by adamhooper** [comment]
This is a good place to ask the question ... but the answer is, "Celery + async is way too hard."

Async_to_sync from a Celery task spins up a new event loop -- and thus, a new RabbitMQ connection. So each message starts a whole new connection! This is grossly inefficient, and it's bad design. I don't recommend it.

(From within Django, async_to_sync is fine and reuses the one event loop.)

We at Workbench ditched Celery and built a job queue with a raw RabbitMQ queue. So there's a raw aioamqp connection for pulling jobs from the queue, and there's the channels_rabbitmq connection for pushing Websocket messages. Two connections total -- much more efficient than a RabbitMQ connection per message.

Celery 5 may resolve this to some extent. I haven't tested or examined how it uses its event queue.

Closing this issue, because it is outside our scope and interests to work with async_to_sync outside of Django Channels.

**Comment by ShaheedHaque** [comment]
Not the answer I'd have liked, but thanks for the prompt and clear reply.
