### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ruslan287** [CJWorkbench/channels_rabbitmq#33]
I tried to use latest version, 2.0.0, as my channels layer and after 24 hours I see a linear memory leak in all my channels containers. Didn't try old versions
**Some more details**

- Libraries:
channels-redis = "==3.2.0"
channels = "==3.0.3"
Django = "==3.1.6"
channels_rabbitmq = "==2.0.0"
sentry-sdk = "==0.19.5"
- Channels usage
I use channels only for WS message for one way - server->clients. My WS usage most of time is to broadcast messages to the all connected clients(WS consumers). I send ~8-10 messages per second to "my_global" channel. My current WS connection numbers are low, depend on time, but current range is 0-500. I have 6 channels instance/containers
- Memory usage - https://i.ibb.co/x7hDbdN/Screen-Shot-2021-02-11-at-19-20-29.png

I don't think this memory leak is on my side? in my business logic code, because I don't have any issues when I use Redis layer(of course, everything is possible)
Maybe, my guess, this issue can be related to Sentry SDK that I use, because ~1 year ago I also had memory leaks with "official" Redis Channel Layer until sentry fix this issue on their SDK.

**Comment by adamhooper** [comment]
Hi @ruslan287,

Thank you for trying out channels_rabbitmq!

I checked our own server logs, and I didn't see a leak. (We, too, use this library primarily to broadcast. And we have similar user counts.)

It could be sentry-sdk or channels-redis. If you uninstall them, does the leak disappear?

Otherwise ... have you configured non-default "expiry", "local_capacity" or "local_expiry" settings? If so, you may not be _leaking_ so much as ... ramping up to a greater memory limit than you expect.

Finally, please check for any warnings in your logs. With default config (which is very conservative), channels_rabbitmq will log warnings when slow clients cause buffers to fill up.

**Comment by ruslan287** [comment]
Hi @adamhooper 
I try to play with settings - increase local_capacity to 500 and decrease expire(+local_expire) to 30, same issue.
Yep, I have log warnings from channels_rabbitmq - **Back-pressuring. Biggest queues...** and **A message (or messages) expired locally. Biggest queues...**
I am not sure about this warnings...

**Comment by adamhooper** [comment]
If 100 Websocket clients are all connected to one server, with local_capacity 500, then here's what the messages mean:

"Expired locally" means one of those 100 clients didn't read the message before expiry. Each message is copied into 100 queues, and at expiry it is removed from all the queues that still contain it. This isn't an "error" in the sense that everything is operating as expected ... but the user experience is bad: the slow consumers are missing messages.

"Back-pressuring" means, 500 messages remain in at least one of the 100 queues. RabbitMQ won't deliver any more messages until one of those 500 messages ends up delivered to all users (or it expires). The user experience is terrible: *all* consumers are missing messages.

As an architect, you cannot guarantee that all these warnings go away. But if they're happening frequently, then tweak your settings or your consumer, or your clients.

We haven't evaluated what happens with 100 concurrent users and local_capacity=1000 ... but it ought to work smoothly. 5000 might be smooth, too, for all I know ... But I haven't benchmarked.

We might have bugs related to expiry. It rarely happens on our servers.

Or there might be a CPU bottleneck? What does CPU usage look like?

At 10msg/s it would take 50s to fill up local_capacity. It should not happen if your expiry is 30s. Is something else wrong?

A design idea: you could make your Django-side consumers "bundle" or "fold" messages before sending, so they don't send 10msg/s to their clients but rather only send the *latest* message when the send buffer allows. Or they could "buffer" messages. It's been a while since I've built consumers, so I don't know off-hand whether this would be easy or hard. But the gist of this paragraph is: the Channel Layer stores a bunch of queues of messages; and as soon as you consume them in every Channels consumer, they leave the Channel Layer data structures.

... Maybe that's what's happening! Maybe you're calling send() and send() and send() and those sends are consuming too much memory?

**Comment by ruslan287** [comment]
This bug was caused by this issue - https://github.com/django/channels/issues/1466
Solved on my side by handling Disconnect excpetion

**Comment by adamhooper** [comment]
So glad to hear you've figured it out! I'll close this issue.

(We at Workbench had been catching that error all along. We didn't realize there would be a leak if we didn't.)

**Comment by adamhooper** [comment]
Let's not catalogue Django Channels' errors in this project's README. If the error is logged correctly, the answer is a web-search away.

It must have been frustrating to battle this bug for months. I know your pain -- trust me, I do.

This README is not the forum for documenting Channels bugs. I encourage you to suggest this fix to the Django Channels project itself.
